// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations (port 5432) - required for Prisma migrations
    // Fallback to DATABASE_URL if DIRECT_URL is not set
    // Note: For Supabase, use DIRECT_URL for migrations and DATABASE_URL for app queries
    url: process.env.DIRECT_URL || process.env.DATABASE_URL || "",
  },
});
